/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Controle.ControleHistorico;
import Controle.ControleProduto;
import entidades.Historico;
import entidades.Produto;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.codehaus.groovy.tools.shell.util.SimpleCompletor;
import relatorio.GerarRelatorio;

/**
 *
 * @author Noite
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        menuCancelar.setText("cancelar produto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTabela = new javax.swing.JPopupMenu();
        menuCancelar = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        telavenda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CP_R = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CP_CODIGO = new javax.swing.JTextField();
        CP_QUANT = new javax.swing.JTextField();
        BT_FIM = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CP_NOTA = new javax.swing.JTable();
        CP_TOTAL = new javax.swing.JLabel();
        telacadastro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CP_COD = new javax.swing.JTextField();
        CP_DESC = new javax.swing.JTextField();
        BT_CADASTRAR = new javax.swing.JButton();
        CP_VALOR = new javax.swing.JFormattedTextField();
        telacadastro1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CP_COD1 = new javax.swing.JTextField();
        BT_CADASTRAR1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        cp_tabela2 = new javax.swing.JTable();
        BT_CADASTRAR2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bt_pesquisar = new javax.swing.JButton();
        cp_pesquisa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cp_tabela = new javax.swing.JTable();
        telarelatório = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CP_INICIO = new javax.swing.JFormattedTextField();
        CP_FIM = new javax.swing.JFormattedTextField();
        BT_GERAR = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        menuCancelar.setText("jMenuItem1");
        menuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelarActionPerformed(evt);
            }
        });
        menuTabela.add(menuCancelar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de venda pastelaria MANÁ");
        setExtendedState(this.MAXIMIZED_BOTH);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(getPreferredSize());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENDAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Código:");

        CP_R.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CP_R.setText("R$");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Quantidade:");

        CP_CODIGO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CP_CODIGO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CP_CODIGOKeyPressed(evt);
            }
        });

        CP_QUANT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CP_QUANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_QUANTActionPerformed(evt);
            }
        });
        CP_QUANT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CP_QUANTKeyPressed(evt);
            }
        });

        BT_FIM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BT_FIM.setText("Finalizar");
        BT_FIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_FIMActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Nota:");

        CP_NOTA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CP_NOTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qtd", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CP_NOTA.setToolTipText("");
        CP_NOTA.setRowHeight(30);
        CP_NOTA.setRowMargin(4);
        CP_NOTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CP_NOTAMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(CP_NOTA);

        CP_TOTAL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        CP_TOTAL.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_FIM)
                    .addComponent(CP_R)
                    .addComponent(CP_TOTAL)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CP_CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CP_QUANT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CP_QUANT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(CP_CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CP_R)
                        .addGap(30, 30, 30)
                        .addComponent(CP_TOTAL)
                        .addGap(70, 70, 70)
                        .addComponent(BT_FIM)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout telavendaLayout = new javax.swing.GroupLayout(telavenda);
        telavenda.setLayout(telavendaLayout);
        telavendaLayout.setHorizontalGroup(
            telavendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telavendaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 335, Short.MAX_VALUE))
        );
        telavendaLayout.setVerticalGroup(
            telavendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telavendaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Venda", new javax.swing.ImageIcon(getClass().getResource("/telas/piggy-bank.png")), telavenda); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO DE PRODUTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Valor:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Descrição:");

        CP_COD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        CP_DESC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        BT_CADASTRAR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BT_CADASTRAR.setText("Cadastrar");
        BT_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CADASTRARActionPerformed(evt);
            }
        });

        try {
            CP_VALOR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CP_VALOR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CP_DESC)
                            .addComponent(CP_VALOR, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(CP_COD))))
                .addGap(513, 513, 513))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CP_COD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CP_VALOR)
                        .addGap(2, 2, 2)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CP_DESC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BT_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telacadastroLayout = new javax.swing.GroupLayout(telacadastro);
        telacadastro.setLayout(telacadastroLayout);
        telacadastroLayout.setHorizontalGroup(
            telacadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telacadastroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 250, Short.MAX_VALUE))
        );
        telacadastroLayout.setVerticalGroup(
            telacadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telacadastroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 392, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de Produto", new javax.swing.ImageIcon(getClass().getResource("/telas/pastel 1.png")), telacadastro); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALTERAÇÃO DE PRODUTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Código:");

        CP_COD1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        BT_CADASTRAR1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BT_CADASTRAR1.setText("SALVAR");
        BT_CADASTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CADASTRAR1ActionPerformed(evt);
            }
        });

        cp_tabela2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cp_tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cp_tabela2.setRowHeight(30);
        cp_tabela2.setRowMargin(4);
        jScrollPane5.setViewportView(cp_tabela2);

        BT_CADASTRAR2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BT_CADASTRAR2.setText("PESQUISAR");
        BT_CADASTRAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CADASTRAR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CP_COD1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BT_CADASTRAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(BT_CADASTRAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CP_COD1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_CADASTRAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BT_CADASTRAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telacadastro1Layout = new javax.swing.GroupLayout(telacadastro1);
        telacadastro1.setLayout(telacadastro1Layout);
        telacadastro1Layout.setHorizontalGroup(
            telacadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telacadastro1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 185, Short.MAX_VALUE))
        );
        telacadastro1Layout.setVerticalGroup(
            telacadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telacadastro1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alteração de Produto", new javax.swing.ImageIcon(getClass().getResource("/telas/pastel 2.png")), telacadastro1); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PESQUISAR PRODUTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bt_pesquisar.setBackground(new java.awt.Color(240, 240, 241));
        bt_pesquisar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        cp_pesquisa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cp_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_pesquisaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Descrição:");

        cp_tabela.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cp_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cp_tabela.setRowHeight(30);
        cp_tabela.setRowMargin(4);
        jScrollPane2.setViewportView(cp_tabela);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(87, 87, 87))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 265, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp_pesquisa)
                    .addComponent(bt_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesquisar Produto", new javax.swing.ImageIcon(getClass().getResource("/telas/search.png")), jPanel4); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RELATÓRIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Tipo de Relatório:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faturamento ", "Consumo Médio", "Mais Vendidos", " " }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Período:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Início:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Fim:");

        try {
            CP_INICIO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CP_INICIO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        try {
            CP_FIM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CP_FIM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        BT_GERAR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BT_GERAR.setText("Gerar");
        BT_GERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_GERARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CP_INICIO, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(CP_FIM)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(BT_GERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CP_FIM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CP_INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(BT_GERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telarelatórioLayout = new javax.swing.GroupLayout(telarelatório);
        telarelatório.setLayout(telarelatórioLayout);
        telarelatórioLayout.setHorizontalGroup(
            telarelatórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telarelatórioLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 746, Short.MAX_VALUE))
        );
        telarelatórioLayout.setVerticalGroup(
            telarelatórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telarelatórioLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 342, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatórios", new javax.swing.ImageIcon(getClass().getResource("/telas/analytics.png")), telarelatório); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BT_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CADASTRARActionPerformed
        // TODO add your handling code here:

        String codigo = CP_COD.getText();
        String valor = CP_VALOR.getText();
        String descricao = CP_DESC.getText();

        String msg = controleProduto.salvar(codigo, valor, descricao);

        JOptionPane.showMessageDialog(this, msg);

        CP_COD.setText("");
        CP_VALOR.setText("");
        CP_DESC.setText("");

    }//GEN-LAST:event_BT_CADASTRARActionPerformed

    private void CP_CODIGOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CP_CODIGOKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String cod = CP_CODIGO.getText();
            int qtd = Integer.parseInt(CP_QUANT.getText());
            Produto p = controleProduto.recuperar(cod);
            double valor = p.getValor() * qtd;
            p.setValorVenda(valor);
            p.setQuantidade(qtd);
            CP_R.setText(controleProduto.recuperarValor(cod));

            valorTotal = valorTotal + valor;
            CP_TOTAL.setText("TOTAL = " + valorTotal);
            listaVenda.add(p);
            preencherNota(listaVenda);

        }
    }//GEN-LAST:event_CP_CODIGOKeyPressed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        String pesquisa = cp_pesquisa.getText();

        List<Produto> lista = controleProduto.pesquisar(pesquisa);

        preencherTabela(lista);
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void cp_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_pesquisaActionPerformed
        // TODO add your handling code here:
        bt_pesquisar.doClick();
    }//GEN-LAST:event_cp_pesquisaActionPerformed

    private void BT_GERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_GERARActionPerformed
        try {
            // TODO add your handling code here:

            Date inicio = formatador.parse(CP_INICIO.getText());
            Date fim = formatador.parse(CP_FIM.getText());
            rel.gerarRelatorio(inicio, fim);
        } catch (ParseException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BT_GERARActionPerformed

    private void BT_FIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_FIMActionPerformed
        try {
            // TODO add your handling code here:
            Historico venda = new Historico();
            venda.setData(formatador.parse(formatador.format(new Date())));
            venda.setValortotal(valorTotal);
            venda.setProduto(listaVenda);

            String msg = controleHistorico.salvar(venda);
            JOptionPane.showMessageDialog(this, msg + "\nTotal = " + valorTotal);

            valorTotal = 0;
            listaVenda.clear();
            CP_CODIGO.setText("");
            CP_QUANT.setText("");
            DefaultTableModel modelo = (DefaultTableModel) CP_NOTA.getModel();
            modelo.setRowCount(0);
        } catch (ParseException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BT_FIMActionPerformed

    private void CP_QUANTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CP_QUANTKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String cod = CP_CODIGO.getText();
            int qtd = Integer.parseInt(CP_QUANT.getText());
            Produto p = controleProduto.recuperar(cod);
            double valor = p.getValor() * qtd;
            p.setValorVenda(valor);
            p.setQuantidade(qtd);
            CP_R.setText(controleProduto.recuperarValor(cod));

            valorTotal = valorTotal + valor;
            CP_TOTAL.setText("TOTAL = " + valorTotal);
            listaVenda.add(p);
            preencherNota(listaVenda);

        }
    }//GEN-LAST:event_CP_QUANTKeyPressed

    private void CP_QUANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_QUANTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_QUANTActionPerformed

    private void CP_NOTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CP_NOTAMouseClicked
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) CP_NOTA.getModel();

        if (evt.getButton() == MouseEvent.BUTTON3 && CP_NOTA.getSelectedRowCount() == 1) {
            int x = evt.getX();
            int y = evt.getY();
            menuTabela.show(CP_NOTA, x, y);
        }
    }//GEN-LAST:event_CP_NOTAMouseClicked

    private void menuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) CP_NOTA.getModel();
        int linha = CP_NOTA.getSelectedRow();
        double itemCancelado = Double.parseDouble(modelo.getValueAt(linha, 2).toString());
        listaVenda.remove(linha);
        preencherNota(listaVenda);

        valorTotal = valorTotal - itemCancelado;
        CP_TOTAL.setText("TOTAL = " + valorTotal);

    }//GEN-LAST:event_menuCancelarActionPerformed

    private void BT_CADASTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CADASTRAR1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) cp_tabela2.getModel();
        String nome =  modelo.getValueAt(0, 1).toString();
        String valor = modelo.getValueAt(0, 2).toString();
     
        produtoAlterar.setDescricao(nome);
        produtoAlterar.setValor(Double.parseDouble(valor));
        String msg = controleProduto.atualizar(produtoAlterar);
        JOptionPane.showMessageDialog(this, msg);
        
    }//GEN-LAST:event_BT_CADASTRAR1ActionPerformed

    private void BT_CADASTRAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CADASTRAR2ActionPerformed
        // TODO add your handling code here:
        String cod = CP_COD1.getText();
        produtoAlterar = controleProduto.recuperar(cod);
        if(produtoAlterar != null) {
            preencherTabela(produtoAlterar);
        } else {
            JOptionPane.showMessageDialog(this, "Código inválido!");
        }
    }//GEN-LAST:event_BT_CADASTRAR2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CADASTRAR;
    private javax.swing.JButton BT_CADASTRAR1;
    private javax.swing.JButton BT_CADASTRAR2;
    private javax.swing.JButton BT_FIM;
    private javax.swing.JButton BT_GERAR;
    private javax.swing.JTextField CP_COD;
    private javax.swing.JTextField CP_COD1;
    private javax.swing.JTextField CP_CODIGO;
    private javax.swing.JTextField CP_DESC;
    private javax.swing.JFormattedTextField CP_FIM;
    private javax.swing.JFormattedTextField CP_INICIO;
    private javax.swing.JTable CP_NOTA;
    private javax.swing.JTextField CP_QUANT;
    private javax.swing.JLabel CP_R;
    private javax.swing.JLabel CP_TOTAL;
    private javax.swing.JFormattedTextField CP_VALOR;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JTextField cp_pesquisa;
    private javax.swing.JTable cp_tabela;
    private javax.swing.JTable cp_tabela2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuCancelar;
    private javax.swing.JPopupMenu menuTabela;
    private javax.swing.JPanel telacadastro;
    private javax.swing.JPanel telacadastro1;
    private javax.swing.JPanel telarelatório;
    private javax.swing.JPanel telavenda;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela(Produto produto) {
        DefaultTableModel modelo = (DefaultTableModel) cp_tabela2.getModel();
        Object[] linha = new Object[5];
        modelo.setRowCount(0);
        linha[0] = produto.getCodigo();
        linha[1] = produto.getDescricao();
        linha[2] = produto.getValor();

        modelo.addRow(linha);

        cp_tabela2.setModel(modelo);
    }

    private void preencherTabela(List<Produto> lista) {

        DefaultTableModel modelo = (DefaultTableModel) cp_tabela.getModel();
        Object[] linha = new Object[5];
        modelo.setRowCount(0);

        for (Produto produto : lista) {
            linha[0] = produto.getCodigo();
            linha[1] = produto.getDescricao();
            linha[2] = produto.getValor();

            modelo.addRow(linha);
        }
        cp_tabela.setModel(modelo);

    }

    private void preencherNota(List<Produto> lista) {

        DefaultTableModel modelo = (DefaultTableModel) CP_NOTA.getModel();
        Object[] linha = new Object[5];
        modelo.setRowCount(0);

        for (Produto produto : lista) {
            linha[0] = produto.getDescricao();
            linha[1] = produto.getQuantidade();
            linha[2] = produto.getValorVenda();

            modelo.addRow(linha);
        }
        CP_NOTA.setModel(modelo);

    }

    ControleProduto controleProduto = new ControleProduto();
    ControleHistorico controleHistorico = new ControleHistorico();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    double valorTotal = 0;
    Produto produtoAlterar;
    List<Produto> listaVenda = new ArrayList();
    GerarRelatorio rel = new GerarRelatorio();
}
